### ISSUE TITLE
exclude expired badges

### ISSUE THREAD

**Issue by jamesgeddes** [michaelcontento/credly-import-action#9]
## Add the option to exclude expired badges

For example, I have two Terraform badges, 002 which is expired, and 003 which is (at the time of writing) current. I would want to be able to exclude the expired one.

## Suggested solution

Add `exclude` input.

```yaml
- uses: michaelcontento/credly-import-action@v1
  with:
    # The user of whom we want to grab the infos
    name: michael-contento
    exclude:
      expired: true
```

If `exclude.expired` == "true" and if `expires_at` ≤ time.now, then pass.

## Future improvement

Making this a general exclusions input would also provide forward compatibility to potentially add other exclusions in a subsequent ticket. For example;

```yaml
- uses: michaelcontento/credly-import-action@v1
  with:
    # The user of whom we want to grab the infos
    name: michael-contento
    exclude:
      expired: true
      issuers:
        - IBM
        - Coursera
      cost: Free


```

## Assignee

I will gladly do this if you want to assign it to me.
